name: Deploy - QA

run-name: ${{ format('Deploy release to {0} - [{1}]', 'QA', github.ref_name) }}

on:
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get version from config file
        id: get-version
        run: |
          VERSION=$(yq '.version' config/qa.yml)
          echo "La versiÃ³n detectada es: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  download-from-s3:
    if: ${{ github.event_name == 'workflow_dispatch' && github.ref_type == 'tag'}}
    uses: kvncont/gh-workflows/.github/workflows/aws-s3-download.yml@main
    with:
      environment: QA
      aws-region: us-east-1
      s3-bucket: kvncont-artifacts
      s3-prefix: releases/QA/${{ github.event.repository.name }}/${{ needs.get-version.outputs.version }}
      s3-file: lambda-${{ needs.get-version.outputs.version }}.zip
      artifact-name: lambda-${{ needs.get-version.outputs.version }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-qa:
    if: ${{ github.event_name == 'workflow_dispatch' && github.ref_type == 'tag'}}
    needs: download-from-s3
    uses: kvncont/gh-workflows/.github/workflows/aws-lambda-cd.yml@main
    with:
      environment: QA
      aws-region: us-east-1
      lambda-name: lambda-python-qa
      artifact-name: lambda-${{ needs.get-version.outputs.version }}
      zip-file: lambda-${{ needs.get-version.outputs.version }}.zip
      env-file: config/qa.yml
      version-description: "Deploy release: [${{ needs.get-version.outputs.version }}]"
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
