name: Deploy - DEV

run-name: Deploy Release ${{ needs.prepare-deploy.outputs.version }}

on:
  workflow_dispatch:

jobs:
  prepare-deploy:
    uses: kvncont/gh-workflows/.github/workflows/get-version-from-yaml.yml@main
    with:
      config-file: config/dev.yml

  download-from-s3:
    needs: prepare-deploy
    uses: kvncont/gh-workflows/.github/workflows/aws-s3-download.yml@main
    with:
      environment: dev
      aws-region: ${{ vars.AWS_PRIMARY_REGION || 'us-east-1' }}
      s3-bucket: ${{ vars.BUCKET_NAME || github.repository_owner }}-artifacts
      s3-prefix: releases/dev/${{ github.event.repository.name }}/${{ needs.prepare-deploy.outputs.version }}
      s3-file: lambda-${{ needs.prepare-deploy.outputs.version }}.zip
      artifact-name: lambda-${{ needs.prepare-deploy.outputs.version }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-dev:
    needs: 
      - prepare-deploy
      - download-from-s3
    uses: kvncont/gh-workflows/.github/workflows/aws-lambda-cd.yml@main
    with:
      environment: dev
      aws-region: ${{ vars.AWS_PRIMARY_REGION || 'us-east-1' }}
      lambda-name: ${{ vars.LAMBDA_NAME || github.event.repository.name }}-dev
      artifact-name: lambda-${{ needs.prepare-deploy.outputs.version }}
      zip-file: lambda-${{ needs.prepare-deploy.outputs.version }}.zip
      env-file: config/dev.yml
      version-description: "Deploy Release: ${{ needs.prepare-deploy.outputs.version }}"
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
