name: Release

run-name: Release [${{ github.event.release.tag_name }}]

on:
  release:
    types:
      - published

jobs:
  build:
    uses: kvncont/gh-workflows/.github/workflows/python-ci.yml@main
    with:
      python-version: 3.14
      zip-name: ${{ vars.LAMBDA_NAME || github.event.repository.name }}-${{ github.event.release.tag_name }}.zip
      artifact-name: ${{ vars.LAMBDA_NAME || github.event.repository.name }}-${{ github.event.release.tag_name }}
      run-tests: false
      run-linting: false

  upload-to-gh-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: ${{ vars.LAMBDA_NAME || github.event.repository.name }}-${{ github.event.release.tag_name }}
          path: ./dist

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*.zip

  upload-to-aws-s3:
    needs: build
    uses: kvncont/gh-workflows/.github/workflows/aws-s3-upload.yml@main
    with:
      aws-region: ${{ vars.AWS_PRIMARY_REGION || 'us-east-1' }}
      aws-role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME || '' }}
      s3-bucket: ${{ vars.BUCKET_NAME || github.repository_owner }}-artifacts
      s3-prefix: releases/${{ github.event.repository.name }}/${{ github.event.release.tag_name }}
      artifact-name: ${{ vars.LAMBDA_NAME || github.event.repository.name }}-${{ github.event.release.tag_name }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
